[package]
name = "espanso-render"
version.workspace = true
authors.workspace = true
license.workspace = true
edition.workspace = true
repository.workspace = true
homepage.workspace = true
description = "Template rendering for espanso"

[dependencies]
anyhow.workspace = true
chrono-tz.workspace = true
chrono.workspace = true
enum-as-inner.workspace = true
log.workspace = true
regex.workspace = true
thiserror.workspace = true
rand = "0.8.6"
sys-locale = "0.1.0"

[lints]
workspace = true
