[package]
name = "espanso-modulo"
version.workspace = true
authors.workspace = true
license.workspace = true
edition.workspace = true
repository.workspace = true
homepage.workspace = true
description = "GUI module (forms, search) for espanso"
exclude = ["vendor/*.zip"]
build = "build.rs"

[dependencies]
serde.workspace = true
anyhow.workspace = true
thiserror.workspace = true
regex.workspace = true

[build-dependencies]
cc.workspace = true
regex.workspace = true
zip = { version = "0.5.12", default-features = false, features = ["deflate", "bzip2"] }
winres = "0.1.11"
glob.workspace = true
ureq = "2"
sha2 = "0.10"

[lints]
workspace = true
