[package]
name = "espanso-engine"
version.workspace = true
authors.workspace = true
license.workspace = true
edition.workspace = true
repository.workspace = true
homepage.workspace = true
description = "Core matching engine for espanso"

[dependencies]
log.workspace = true
anyhow.workspace = true
thiserror.workspace = true
crossbeam.workspace = true
pulldown-cmark = "0.13.0"
html2text = "0.12.0"
unicode-segmentation = "1.9.0"

[lints]
workspace = true
