[package]
name = "espanso-match"
version.workspace = true
authors.workspace = true
license.workspace = true
edition.workspace = true
repository.workspace = true
homepage.workspace = true
description = "Text matching algorithms for espanso"

[dependencies]
log.workspace = true
regex.workspace = true
unicase = "2.6.0"

[lints]
workspace = true
