[package]
name = "espanso-mac-utils"
version.workspace = true
authors.workspace = true
license.workspace = true
edition.workspace = true
repository.workspace = true
homepage.workspace = true
description = "macOS utility functions for espanso"
build = "build.rs"

[dependencies]
regex.workspace = true

[build-dependencies]
cc.workspace = true

[lints]
workspace = true
