[package]
name = "espanso-info"
version.workspace = true
authors.workspace = true
license.workspace = true
edition.workspace = true
repository.workspace = true
homepage.workspace = true
description = "System information gathering for espanso"
build = "build.rs"

[features]
# If the wayland feature is enabled, all X11 dependencies will be dropped
wayland = []

[dependencies]
log.workspace = true
anyhow.workspace = true
espanso-package = { path = "../espanso-package", version = "2.4.0" }

[lints]
workspace = true

[target.'cfg(windows)'.dependencies]
widestring.workspace = true

[build-dependencies]
cc.workspace = true
