[package]
name = "espanso-config"
version.workspace = true
authors.workspace = true
license.workspace = true
edition.workspace = true
repository.workspace = true
homepage.workspace = true
description = "Configuration parsing and management for espanso"

[dependencies]
log.workspace = true
anyhow.workspace = true
thiserror.workspace = true
serde.workspace = true
serde_norway.workspace = true
glob.workspace = true
regex.workspace = true
dunce = "1.0.1"
walkdir.workspace = true
enum-as-inner.workspace = true
ordered-float = "2.0"
indoc = "1.0.3"

[dev-dependencies]
tempdir.workspace = true
tempfile = "3.2.0"
mockall = "0.9.1"

[lints]
workspace = true
